[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1.17"
sha1 = "0.10.1"
base64 = "0.13.0"
rand = "0.8.0"
thiserror = "1.0.23"
byteorder = "1.3.2"
